export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/'
export const FAVORITE_ROUTE = '/favorite'
export const RECEPTE_ROUTE = '/recepte'